#!/bin/sh

sudo timedatectl set-ntp true

echo "Installing the big packages.."

sudo pacman --noconfirm -Sy -<afterlist

sudo touch /var/spool/cron/air
sudo echo "0 * * * * sudo pacman -Sy" >> /var/spool/cron/air

sudo systemctl enable cronie.service
sudo systemctl start cronie.service

echo "Configuring and logging in to github.."
gh auth login

#downloading backgrounds and extracting them
wget https://download948.mediafire.com/dlb4h4d7m9cgS5mfUJogx3ufGZ3LEtQQvpEFfCiVCvqekAgbFqESU5mZS6_qBB0PDekk6lvIj06kJEtGFpr46s-QbS9_c78/i9hk1f0yokb3uqf/backgrounds.tar /home/air/downloads

tar -xvf backgrounds.tar -C /home/air



