#!/bin/bash

# Arch custom install script
# written by and mostly for:
#     _    ___ ____  _  ___   _
#    / \  |_ _|  _ \| |/ / \ | |
#   / _ \  | || |_) | ' /|  \| |
#  / ___ \ | ||  _ <| . \| |\  |
# /_/   \_\___|_| \_\_|\_\_| \_|
#
# github.com/hamedxyz

#part1
echo "Welcome to hamedxyz's arch install script"
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15/" /etc/pacman.conf
lsblk
read -p "Drive (sd_): " drive
cfdisk /dev/$drive
clear
lsblk
read -p "Boot partition (sd_#): " bootpart
read -p "Linux (/) partition (sd_#): " partition
read -p "Swap partition (if u created one) [swappart(sd_#) /n] " swappart
mkfs.ext4 /dev/$bootpart
mkfs.ext4 /dev/$partition
if [[ "$swappart" != n ]] ; then
  mkswap /dev/$swappart
  swapon /dev/$swappart
fi

#read -p "Did you also create efi partition? [y/n]" answer
#if [[ $answer = y ]] ; then
#  echo "Enter EFI partition: "
#  read efipartition
#  mkfs.vfat -F 32 $efipartition
#fi

clear
lsblk
mount /dev/$partition /mnt
mkdir /mnt/boot
mount /dev/$bootpart /mnt/boot
lsblk
pacman --noconfirm -Sy archlinux-keyring
pacman-key --init && pacman-key --populate archlinux
pacstrap /mnt base base-devel linux linux-firmware vim
genfstab -U /mnt >> /mnt/etc/fstab
sed '1,/^#part2$/d' `basename $0` > /mnt/archinstall2.sh
chmod +x /mnt/archinstall2.sh
cd /mnt
arch-chroot /mnt ./archinstall2.sh
exit

#part2
clear
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15/" /etc/pacman.conf

# all user input is at the start for convenience, u just answer the questions together n watch/ wait for it to complete the installation (pretty generic when it comes to os installers doe nothing special)

read -p "use default timezone? (Africa/Tunis?) [y] or enter ur own timezone [Continent/City] " timezn

read -p "Hostname: " hostname
passwd

lsblk
read -p "Drive to install Grub bootloader on (sd_): " drive

read -p "Username: " name
passwd $name

read -p "Install NVIDIA proprietary drivers? [y/n] " answer1

read -p "Install ALL Archstrike PenTesting packages? [y/n] " answer2

read -p "Additional packages you'd like to install? [y/n] " answer3
if [[ "$answer3" = y ]] ; then
  read -p "Which packages? " packages
fi


if [[ "$timezn" != y ]] ; then
    ln -sf /usr/share/zoneinfo/$timezn /etc/localtime
    hwclock --systohc
    timedatectl set-timezone $timezn
else
    ln -sf /usr/share/zoneinfo/Africa/Tunis /etc/localtime
    hwclock --systohc
    timedatectl set-timezone Africa/Tunis
fi
#timedatectl set-ntp true

echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
echo "ar_TN.UTF-8 UTF-8" >> /etc/locale.gen
echo "ja_JP.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf
echo $hostname > /etc/hostname
echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /etc/hosts
pacman --noconfirm -S networkmanager grub
systemctl enable NetworkManager
grub-install /dev/$drive
grub-mkconfig -o /boot/grub/grub.cfg

# make pacman colorful, concurrent downloads and Pacman eye-candy.
grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf
# Use all cores for compilation.
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf

# dont ask for password when using sudo (i think the first login is enough to confirm user identity + its a pain having to type a long and complex password everytime u try to do anyth with higher user permissions, at least on my personal computer which 99.9% of the time im the only one using it)
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
echo "Defaults !tty_tickets" >> /etc/sudoers
useradd -mg wheel "$name"
chown -R $name:wheel /home/$name
chmod 700 /home/$name

# gets rid of beep?
rmmod pcspkr
echo "blacklist pcspkr" >/etc/modprobe.d/nobeep.conf


echo "Installing needed base-devel packages.."
pacman --noconfirm -S --needed base-devel git


echo "Cloning and Moving dotfiles from github.."
sudo -u $name git clone https://github.com/hamedxyz/dotfiles /home/$name/dotfiles
mv /home/$name/dotfiles/* /home/$name/dotfiles/.* /home/$name
sudo -u $name mkdir -p /home/$name/downloads
sudo -u $name mkdir -p /home/$name/programs
sudo -u $name mkdir -p /home/$name/repos
sudo -u $name mkdir -p /home/$name/music
sudo -u $name mkdir -p /home/$name/portal
sudo -u $name mkdir -p /home/$name/stuff

# a few packages in pacmanlist are from the multilib repo
echo "[multilib]" >> /etc/pacman.conf
echo "Include = /etc/pacman.d/mirrorlist" >> /etc/pacman.conf
echo "" >> /etc/pacman.conf

echo "Installing packages from pacmanlist.."
curl -LO raw.githubusercontent.com/hamedxyz/archinstall/main/pacmanlist
pacman --noconfirm -Sy
while read p; do
    pacman --noconfirm -S "$p"
done <pacmanlist
# pacman -Rsu --noconfirm $(comm -23 <(pacman -Qq | sort) <(sort packagelist))

echo "Installing the Aur Helper (yay).."
cd /home/$name/repos
sudo -u $name git clone https://aur.archlinux.org/yay.git
chown -R $name:wheel yay
cd yay
sudo -u $name makepkg --noconfirm -si
cd /tmp
sudo -u $name yay -Syu --noconfirm

echo "Installing AUR packages from the list.."
curl -LO raw.githubusercontent.com/hamedxyz/archinstall/main/aurlist
while read p; do
    sudo -u $name yay -S --noconfirm "$p"
done <aurlist

# making sure pulse is gone and pipewire is installed, i think it's downloaded by default with other packages while setting up the kernel
echo "Installing a few additional packages.."
pacman --noconfirm -R pulseaudio
pacman --noconfirm -S lib32-pipewire

#part3
echo "Cloning and Building the window manager & other programs from github repos.."
export repodir="/home/$name/.local/src"
sudo -u $name mkdir -p "$repodir"
#chown -R "$name":wheel "$(dirname "$repodir")"

sudo -u $name git clone https://github.com/hamedxyz/dwm $repodir/dwm
make -C $repodir/dwm install

sudo -u $name git clone https://github.com/hamedxyz/dwmblocks $repodir/dwmblocks
make -C $repodir/dwmblocks install

sudo -u $name git clone https://github.com/hamedxyz/st $repodir/st
make -C $repodir/st install

sudo -u $name git clone https://github.com/hamedxyz/dmenu $repodir/dmenu
make -C $repodir/dmenu install

sudo -u $name git clone https://github.com/hamedxyz/othersrc $repodir/othersrc
make -C $repodir/othersrc/sxiv install
make -C $repodir/othersrc/slock install
make -C $repodir/othersrc/screenpenbuild install
make -C $repodir/othersrc/sent install


git clone https://github.com/hamedxyz/pitchblackgtk /usr/share/themes/pitchblackgtk

echo "Installing nvim plugins//"
cp /usr/share/vim/vim90/defaults.vim /usr/share/nvim/runtime/
sudo -u $name nvim -c "PlugInstall|q|q"
chsh -s /bin/zsh "$name"
sudo -u $name mkdir /home/$name/.local/share/zsh
rm /bin/sh
ln -s /bin/dash /bin/sh

# chaotic contains a few packages that i might concider, for example the XanMod kernel (for high performance, low latency, gaming and recording)
echo "Adding Chaotic-aur mirrorlist.."
pacman-key --recv-key FBA220DFC880C036 --keyserver keyserver.ubuntu.com
pacman-key --lsign-key FBA220DFC880C036
pacman --noconfirm -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst' 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'
echo "[chaotic-aur]" >> /etc/pacman.conf
echo "Include = /etc/pacman.d/chaotic-mirrorlist" >> /etc/pacman.conf
echo "" >> /etc/pacman.conf
pacman -Sy --noconfirm

# a repository full of pentesting tools, just in case, can come in handy
echo "Adding Archstrike mirrorlist.."
echo "[archstrike]" >> /etc/pacman.conf
echo "Server = https://mirror.archstrike.org/\$arch/\$repo" >> /etc/pacman.conf
pacman -Sy --noconfirm
pacman-key --init
dirmngr < /dev/null
pacman-key -r 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
pacman-key --lsign-key 9D5F1C051D146843CDA4858BDE64825E7CBC0D51
pacman --noconfirm -S archstrike-keyring archstrike-mirrorlist
sed -i '$d' /etc/pacman.conf
echo "Include = /etc/pacman.d/archstrike-mirrorlist" >> /etc/pacman.conf
pacman -Sy --noconfirm

if [[ "$answer1" = y ]] ; then
    mkdir -p /etc/X11/xorg.conf.d
    mv /home/$name/dotfiles/nvidia/20-nvidia.conf /etc/X11/xorg.conf.d
    sleep 1s
    pacman --noconfirm -S --needed nvidia nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader
fi

if [[ "$answer2" = y ]] ; then
    #read -p "You will need to confirm the operations in order to avoid errors"
    pacman -Ss --noconfirm archstrike --needed
fi

if [[ $answer3 = y ]] ; then
    pacman -S --noconfirm $packages
fi

rm -rf /home/$name/dotfiles

# blocked ips
cat /home/$name/.loacal/share/.ips >> /etc/hosts


echo "Preparing afterinstall script list installer.."
curl -LO raw.githubusercontent.com/hamedxyz/archinstall/main/afterinstall
curl -LO raw.githubusercontent.com/hamedxyz/archinstall/main/afterlist
chmod +x afterinstall


clear
echo "Installation Complete. Please reboot now."

sleep 2s
exit
