#!/bin/bash

#Arch install script
#written by and customized specifically for:
#    _    ___ ____
#   / \  |_ _|  _ \
#  / _ \  | || |_) |
# / ___ \ | ||  _ <
#/_/   \_\___|_| \_\
#
#part1
echo "Welcome to air's arch install script"
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15/" /etc/pacman.conf
loadkeys us
timedatectl set-ntp true
lsblk
echo "Enter the drive: "
read drive
cfdisk $drive
echo "Enter the linux partition: "
read partition
mkfs.ext4 $partition
echo "Enter the boot partition: "
read bootpart
mkfs.ext4 $bootpart

#read -p "Did you also create efi partition? [y/n]" answer
#if [[ $answer = y ]] ; then
#  echo "Enter EFI partition: "
#  read efipartition
#  mkfs.vfat -F 32 $efipartition
#fi

mount $partition /mnt
mkdir /mnt/boot
mount $bootpart /mnt/boot
lsblk
pacman --noconfirm -Sy archlinux-keyring
pacman-key --init && pacman-key --populate archlinux
pacstrap /mnt base base-devel linux linux-firmware vim
genfstab -U /mnt >> /mnt/etc/fstab
sed '1,/^#part2$/d' `basename $0` > /mnt/archinstall2.sh
chmod +x /mnt/archinstall2.sh
cd /mnt
arch-chroot /mnt ./archinstall2.sh
exit

#part2
clear
pacman -S --noconfirm sed
sed -i "s/^#ParallelDownloads = 5$/ParallelDownloads = 15/" /etc/pacman.conf
ln -sf /usr/share/zoneinfo/Africa/Tunis /etc/localtime
hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
echo "KEYMAP=us" > /etc/vconsole.conf
echo "Hostname: "
read hostname
echo $hostname > /etc/hostname
echo "127.0.0.1       localhost" >> /etc/hosts
echo "::1             localhost" >> /etc/hosts
echo "127.0.1.1       $hostname.localdomain $hostname" >> /etc/hosts
passwd
pacman --noconfirm -S networkmanager grub git
systemctl enable NetworkManager
echo "Enter the drive: "
read drive
grub-install $drive
grub-mkconfig -o /boot/grub/grub.cfg

# Make pacman colorful, concurrent downloads and Pacman eye-candy.
grep -q "ILoveCandy" /etc/pacman.conf || sed -i "/#VerbosePkgLists/a ILoveCandy" /etc/pacman.conf
sed -Ei "s/^#(ParallelDownloads).*/\1 = 5/;/^#Color$/s/#//" /etc/pacman.conf
# Use all cores for compilation.
sed -i "s/-j2/-j$(nproc)/;/^#MAKEFLAGS/s/^#//" /etc/makepkg.conf

curl -LO raw.githubusercontent.com/airkn/archinstall/main/pacmanlist

pacman -S --noconfirm --needed $(comm -12 <(pacman -Slq | sort) <(sort pacmanlist))
#pacman -Rsu --noconfirm $(comm -23 <(pacman -Qq | sort) <(sort packagelist))


#rm /bin/sh
#ln -s dash /bin/sh
echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers
echo "Defaults !tty_tickets" >> /etc/sudoers
echo "Enter Username: "
read name
useradd -m -g wheel -s /bin/zsh "$name"
usermod -a -G wheel "$name" && mkdir -p /home/"$name" && chown "$name":wheel /home/"$name"
passwd $name
export repodir="/home/$name/.local/src"
mkdir -p "$repodir"
chown -R "$name":wheel "$(dirname "$repodir")"

#gets rid of beep?
rmmod pcspkr
echo "blacklist pcspkr" >/etc/modprobe.d/nobeep.conf

curl -LO raw.githubusercontent.com/airkn/archinstall/main/aurlist

yay -S --noconfirm --needed $(comm -12 <(yay -Slq | sort) <(sort aurlist))

cd /opt
git clone https://aur.archlinux.org/yay-git.git
chown -R air:air ./yay-git
cd yay-git
makepkg -si
cd /

#part3

git clone https://github.com/airkn/dotfiles /home/$name/dotfiles
mv /home/$name/dotfiles/* /home/$name/dotfiles/.* /home/$name

mkdir /home/$name/.local/src

git clone https://github.com/airkn/dwm $repodir/dwm
make -C $repodir/dwm clean install

git clone https://github.com/airkn/dwmblocks $repodir/dwmblocks
make -C $repodir/dwmblocks clean install

git clone https://github.com/airkn/st $repodir/st
make -C $repodir/st clean install

git clone https://github.com/airkn/dmenu $repodir/dmenu
make -C $repodir/dmenu clean install

git clone https://github.com/airkn/othersrc $repodir/othersrc
make -C $repodir/othersrc/sxiv clean install
make -C $repodir/othersrc/slock clean install


mkdir /home/$name/downloads

pacman -Syu
pacman -S --noconfirm lib32-pipewire

echo "Would you like to install NVIDIA proprietary drivers? [y/n] "
read answer1
if [[ $answer1 = y ]] ; then
  mkdir -p /etc/X11/xorg.conf.d
  mv /home/$name/dotfiles/nvidia/20-nvidia.conf /etc/X11/xorg.conf.d
  sleep 1s
  pacman -S --noconfirm --needed nvidia nvidia-utils lib32-nvidia-utils nvidia-settings vulkan-icd-loader lib32-vulkan-icd-loader
fi

echo "Any additional packages you'd like to install? [y/n] "
read answer2
if [[ $answer2 = y ]] ; then
  echo "Which packages? "
  read packages
  pacman -S --noconfirm $packages
fi

rm -rf /home/$name/dotfiles

clear
echo "Installation Complete! Please reboot now!"

sleep 2s
exit
